# Generated by Django 5.2.1 on 2025-05-20 23:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="Cadastro de Pessoa Física. Somente números.",
                        max_length=11,
                        null=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "date_birth",
                    models.DateField(
                        blank=True,
                        help_text="Data de nascimento do usuário.",
                        null=True,
                        verbose_name="Data de nascimento",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Rua, avenida, etc.",
                        max_length=255,
                        null=True,
                        verbose_name="Logradouro",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Número do endereço.",
                        max_length=20,
                        null=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        help_text="Complemento do endereço (opcional).",
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True,
                        help_text="Bairro do endereço.",
                        max_length=255,
                        null=True,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Cidade do endereço.",
                        max_length=255,
                        null=True,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "state",
                    localflavor.br.models.BRStateField(
                        blank=True,
                        help_text="UF do estado (ex: SP, RJ).",
                        max_length=2,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        help_text="CEP do endereço.",
                        max_length=10,
                        null=True,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Brazil",
                        help_text="País do endereço.",
                        max_length=64,
                        null=True,
                        verbose_name="País",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o endereço está ativo.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário ao qual este endereço pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Telefone"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        help_text="Tipo do contato: Email, Telefone ou WhatsApp.",
                        max_length=16,
                        verbose_name="Tipo de contato",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Valor do contato (e-mail, número, etc).",
                        max_length=255,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o contato está ativo.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário ao qual este contato pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
    ]
